import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Heropage from '../components/Heropage'
import Findpoll from '../components/Findpoll'
import Signin from '../components/Signin'

import dbConnect from "../utils/dbConnect"

dbConnect();


export default function Home() {
  return (
    <>
      <Head>
        <title>Polling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heropage/>
      <Findpoll/>
      <Signin/>
    </>
  )
}
